services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4571:4571"            # LocalStack Edge Port
    environment:
      - SERVICES=s3,lambda,dynamodb,apigateway
      - DEBUG=1
      - WEB_UI=1
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - "./localstack_data:/var/lib/localstack/data"
      - "/var/run/docker.sock:/var/run/docker.sock" # Required for lambda to work properly