services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_main
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4571:4571"            # LocalStack Edge Port
    environment:
      - SERVICES=s3,lambda,dynamodb,apigateway
      - DEBUG=1
      - WEB_UI=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./localstack_data:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock" # Required for lambda to work